### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by realyukii** [itzngga/Roxy#25]
Saya coba buat instance whatsapp client dengan konfigurasi seperti ini (full code-nya ada di [repo ini](https://github.com/Reyuki-san/botwhatsapp)):

```go
package main

import (
	"fmt"
	"log"
	"os"
	"os/signal"
	"syscall"

	"github.com/itzngga/goRoxy/core"
	"github.com/itzngga/goRoxy/options"
	"github.com/joho/godotenv"

	_ "botwhatsapp/command"
	_ "github.com/lib/pq"
)

func main() {
	err := godotenv.Load()
	if err != nil {
		log.Fatalln("Error loading .env file")
	}

	options := options.Options{
		HostNumber:  os.Getenv("HOST_NUMBER"),
		StoreMode:   "postgres",
		PostgresDsn: fmt.Sprintf("user=%s password=%s dbname=%s port=%s sslmode=disable TimeZone=Asia/Jakarta", os.Getenv("PG_USERNAME"), os.Getenv("PG_PASSWORD"), os.Getenv("PG_DB_NAME"), os.Getenv("PG_PORT")),

		WithCommandLog: true,
		LogLevel:       "DEBUG",

		WithHelpCommand: true,
		HelpTitle:       "Kurisu Bot",
		HelpDescription: "Konniciwa minna san~",
		HelpFooter:      "2023 copyright kurisu bot",
	}

	fmt.Println(&options)
	return

	app := core.NewGoRoxyBase(options)

	c := make(chan os.Signal)
	signal.Notify(c, os.Interrupt, syscall.SIGTERM)
	<-c
	app.Shutdown()
}
```

dan mendapatkan error seperti berikut pada saat `go run main.go`:

```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0xa714dc]

goroutine 1 [running]:
github.com/itzngga/goRoxy/core.(*App).PrepareClient(0xc00012c780)
        /home/reyuki/go/pkg/mod/github.com/itzngga/go!roxy@v0.0.0-202301190802
15-fe6e79f38262/core/app.go:135 +0x31c
github.com/itzngga/goRoxy/core.NewGoRoxyBase({{0xc0001442ac, 0x11}, {0xbfe641,
 0x8}, {0xbfa611, 0x5}, {0xc00010e3c0, 0x59}, {0x0, 0x0}, ...})
        /home/reyuki/go/pkg/mod/github.com/itzngga/go!roxy@v0.0.0-202301190802
15-fe6e79f38262/core/app.go:47 +0x1b0
main.main()
        /home/reyuki/Desktop/practice/botwhatsapp/main.go:37 +0x298
exit status 2
```

apakah ada yang saya lewati? atau ada bug di package goRoxynya?

**Comment by realyukii** [comment]
Hmm ternyata ga harus pass `HostNumber` ya... ku hapus udah bisa 👍 
tapi masih penasaran kalo di pass `HostNumber`-nya kok error ya :v

**Comment by itzngga** [comment]
@Reyuki-san oke nanti di cek, karena agak males mtc ini lib wkwk

**Comment by Reyuki-san** [comment]
@itzngga kak link group kak onegai kak :"(
